### ISSUE TITLE
[ Week 4 ] 4주차 워크북 미션 -02

### ISSUE THREAD

**Issue by phjlia2430** [DS-UMC-7th/UMC-7th-Lia#11]
### 🛠 Mission

영화 상세 페이지 제작

### 📝 To-do

- [x] 해당 영화 컴포넌트를 클릭시, 상세 페이지로 이동하기
- [x] movieId를 활용하여, 영화 상세 페이지 정보를 받아오기
- [x] 추가적으로, 감독/출연 데이터 또한 movieId를 활용하여, Credit 정보를 받아오기
- [x] custom-hook을 이용하여, loading 처리와 error 처리하기

### 🔍 접근 방법

info정보와 credit정보를 가져오는 파일을 만들고 MoviesDetail에서 보여주는 방식으로 구현하였음
토큰이 저번 미션과 달라서 따로 .env에 변수선언하고 새로운 커스텀훅 파일 만들어서 적용하였음
