### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션

### ISSUE THREAD

**Issue by phjlia2430** [DS-UMC-7th/UMC-7th-Lia#15]
### 🛠 Mission

1. 회원가입 / 로그인 API 연결
2. QueryParameter 활용 검색 기능 구현

### 📝 To-do

- [x] 회원가입
- [x] 로그인
- [x] 로그인 후 메인 페이지 이동
- [x] 로그아웃
- [x] 영화 제목 검색어를 입력하지 않는 경우 (/search 경로에 처음 온 경우)
- [x] 영화 제목 검색어를 입력한 경우
- [x] 영화 검색어를 입력했으나, 해당 검색어의 영화 데이터가 존재하지 않는 경우
- [x] 로딩 중인 경우

### 🔍 접근 방법
style분리방법
Axios Interceptor를 활용해 토큰 재발급
기존에 만들었던 컴포넌트 활용해 검색 결과물 출력
Skeleton UI적용
