### ISSUE TITLE
[ Week 7 ] 7주차 워크북 미션1, 미션2

### ISSUE THREAD

**Issue by phjlia2430** [DS-UMC-7th/UMC-7th-Lia#19]
### 🛠 Mission

미션 1 : Project에 useQuery 를 활용하기
미션 2 : Project에 useInfiniteQuery 를 활용하기

### 📝 To-do

미션 1
- [x] 지금까지, custom-hook을 활용하여, 불러온 get 요청의 데이터들을 먼저 `useQuery` 를 활용한 데이터 호출로 변경
- [x] `queryKey`를 명확하게 설정하고 `useQuery`의 반환 값을 활용하여, loading과 error 처리를 진행
- [x] 로딩 처리에서 Skeleton UI를 활용

미션 2
- [x] 지금까지, 미션 1에서 useQuery를 활용하여, 불러온 get 요청의 데이터들을 먼저 useInfiniteQuery 를 활용한 데이터 호출로 변경
- [x] `queryKey`를 명확하게 설정
- [x]  `useQuery`의 반환 값을 활용하여, `loading`과 `error` 처리
- [x]  로딩 처리에서 Skeleton UI, Loading Spinner 활용

### 🔍 접근 방법
TanStack Query공식문서 참고
(https://tanstack.com/query/latest)
