### ISSUE TITLE
[ Week 8] 8주차 워크북 미션 3

### ISSUE THREAD

**Issue by phjlia2430** [DS-UMC-7th/UMC-7th-Lia#27]
### 🛠 Mission

기존, 영화 사이트 리팩토링

### 📝 To-do

- [x]  `POST` 요청시, `useMutation`을 활용한 코드로 리팩토링
- [x]  회원가입 api를 `useMutation`을 활용한 코드로 수정
- [x]  로그인 api를 `useMutation`을 활용한 코드로 수정
- [x]  https://watcha.com/ 홈페이지를 보며, 2개의 페이지 이상 최대한 비슷하게 따라 만들어서 기존 프로젝트에 추가

### 🔍 접근 방법

useMutation사용해 리팩토링, 기존 영화카테고리 코드 참고해 tv정보 받아오기
