### ISSUE TITLE
[ Week 9 ] 9주차 워크북 미션 1,2

### ISSUE THREAD

**Issue by phjlia2430** [DS-UMC-7th/UMC-7th-Lia#31]
### 🛠 Mission

1. redux-toolkit 활용 UMC PlayList 제작
2. Modal Slice 활용하여, 모달 기능 추가

### 📝 To-do

미션 1
- [x]  `redux-toolkit`를 사용하기 위해서 `Provider`를 연결
- [x]  `configureStore`를 활용해, 중앙 저장소를 만들기
- [x]  cart에 관한 상태이니 `cartSlice`를 만들어주고, 중앙 저장소에 연결
- [x]  increase action 기능 구현, decrease action 기능 구현
- [x]  removeItem action 기능 구현
- [x]  clearCart action 기능 구현
- [x]  calculateTotals action 기능 구현

미션 2
- [x]  Cart Slice, Modal Slice 별도로 파일을 분리
- [x]  Modal이 나오고, 아니요 버튼을 누르면 모달 창이 사라지는가?
- [x]  Modal이 나오고, 네 버튼을 누르면 모든 쇼핑카트의 목록들이 제거 되고, 모달 창이 사라지는가?
- [x]  이전 미션에서 만든 `clearCart Action`을 활용했는가?
- [x]  Reducer를 활용해서 만들었는가? (useState를 사용하지 않고, reducer를 통해)

### 🔍 접근 방법
redux-toolkit 사용, CartSlice생성 후 store연결
ModalSlice생성 후 store 연결, index.html에 root말고 portal추가
